"use client";

import { useEffect, useState } from "react";
import { Button, Card, Feedback } from "@gestionresidencial/shared-ui";
import { communityService, type CommonArea } from "@/services/community-service";

export function CommonAreasManager() {
  const [areas, setAreas] = useState<CommonArea[]>([]); const [notice, setNotice] = useState(""); const [blocking, setBlocking] = useState<CommonArea | null>(null); const [reason, setReason] = useState("");
  useEffect(() => { communityService.getCommonAreas().then(setAreas); }, []);
  async function setAvailability(area: CommonArea, available: boolean, blockReason?: string) { const changed = await communityService.updateCommonAreaAvailability(area.id, available, blockReason); setAreas((all) => all.map((item) => item.id === changed.id ? changed : item)); setNotice(available ? `${area.name} está disponible para reservas.` : `${area.name} fue bloqueada para nuevas reservas.`); setBlocking(null); }
  return <div className="community-page"><div className="page-heading community-heading"><div><span className="gr-eyebrow">Gestión de espacios</span><h1>Zonas comunes</h1><p>Controla la disponibilidad y consulta las reservas de la comunidad.</p></div><span className="post-count">{areas.filter((area) => area.available).length} disponibles</span></div>{notice && <Feedback>{notice}</Feedback>}<div className="area-grid">{areas.map((area) => <Card className="area-card" key={area.id}><div className="area-top"><div><span className={`availability ${area.available ? "open" : "closed"}`}>{area.available ? "Disponible" : "Bloqueada"}</span><h2>{area.name}</h2><p>{area.description}</p></div><button className="toggle" aria-label={`Cambiar disponibilidad de ${area.name}`} aria-pressed={area.available} onClick={() => area.available ? (setBlocking(area), setReason("")) : setAvailability(area, true)}><span /></button></div>{!area.available && <div className="block-reason"><strong>Motivo del bloqueo</strong><span>{area.blockReason}</span></div>}<div className="reservation-header"><h3>Reservas próximas</h3><span>{area.reservations.length}</span></div>{area.reservations.length ? <div className="reservation-list">{area.reservations.map((reservation) => <div className="reservation" key={reservation.id}><div><strong>{reservation.resident}</strong><small>{reservation.apartment}</small></div><div><strong>{reservation.date}</strong><small>{reservation.time} · {reservation.guests} personas</small></div></div>)}</div> : <p className="no-reservations">No hay reservas próximas para esta zona.</p>}<Button variant="secondary" onClick={() => area.available ? (setBlocking(area), setReason("")) : setAvailability(area, true)}>{area.available ? "Bloquear zona" : "Habilitar zona"}</Button></Card>)}</div>{blocking && <div className="modal-backdrop" role="presentation"><Card className="block-modal" role="dialog" aria-modal="true" aria-labelledby="block-title"><h2 id="block-title">Bloquear {blocking.name}</h2><p>Los residentes no podrán hacer nuevas reservas mientras la zona esté bloqueada.</p><label>Motivo del bloqueo<textarea value={reason} required onChange={(event) => setReason(event.target.value)} placeholder="Ej. Mantenimiento de cubierta" /></label><div><Button variant="ghost" onClick={() => setBlocking(null)}>Cancelar</Button><Button disabled={!reason.trim()} onClick={() => setAvailability(blocking, false, reason.trim())}>Confirmar bloqueo</Button></div></Card></div>}</div>;
}
