FROM node:22-alpine

WORKDIR /app

ENV NEXT_TELEMETRY_DISABLED=1
ARG BACKEND_API_URL=http://localhost:4000
ARG NEXT_PUBLIC_AUTH_UI_URL=http://localhost:3002
ARG NEXT_PUBLIC_COMMON_UI_URL=http://localhost:3000
ARG NEXT_PUBLIC_WALL_UI_URL=http://localhost:3003
ARG NEXT_PUBLIC_BOOKING_UI_URL=http://localhost:3004
ARG NEXT_PUBLIC_GATE_UI_URL=http://localhost:3005
ARG NEXT_PUBLIC_BILLING_UI_URL=http://localhost:3007
ENV BACKEND_API_URL=$BACKEND_API_URL
ENV NEXT_PUBLIC_AUTH_UI_URL=$NEXT_PUBLIC_AUTH_UI_URL
ENV NEXT_PUBLIC_COMMON_UI_URL=$NEXT_PUBLIC_COMMON_UI_URL
ENV NEXT_PUBLIC_WALL_UI_URL=$NEXT_PUBLIC_WALL_UI_URL
ENV NEXT_PUBLIC_BOOKING_UI_URL=$NEXT_PUBLIC_BOOKING_UI_URL
ENV NEXT_PUBLIC_GATE_UI_URL=$NEXT_PUBLIC_GATE_UI_URL
ENV NEXT_PUBLIC_BILLING_UI_URL=$NEXT_PUBLIC_BILLING_UI_URL

COPY package.json ./
RUN npm install --no-audit --no-fund

COPY . .
RUN npm run build

EXPOSE 3001
CMD ["npm", "run", "start"]
